In [208]:
#Importo todo. 
import pandas as pd
import numpy as np

In [209]:
#1. Carga los datos de cada pestaña del archivo US_Regional_Sales_Data.xlsx en un
#DataFrame independiente. (hint: Puedes obtener los nombres de las hojas usando
#pd.ExcelFile(archivo).sheet_names)

In [210]:
pd.read_excel("US_Regional_Sales_Data.xlsx")

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Price,Unit Cost
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,259,12,5,0.075,1963.1,1001.181
1,SO - 000102,Online,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-22,2018-07-02,USD,14,20,196,27,3,0.075,3939.6,3348.660
2,SO - 000103,Distributor,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-21,2018-07-01,USD,21,16,213,16,1,0.050,1775.5,781.220
3,SO - 000104,Wholesale,WARE-NMK1003,2017-12-31,2018-05-31,2018-06-02,2018-06-07,USD,28,48,107,23,8,0.075,2324.9,1464.687
4,SO - 000105,Distributor,WARE-NMK1003,2018-04-10,2018-05-31,2018-06-16,2018-06-26,USD,22,49,111,26,8,0.100,1822.4,1476.144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,2020-09-26,2020-12-30,2021-01-07,2021-01-14,USD,9,41,339,29,1,0.075,234.5,121.940
7987,SO - 0008088,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-02,2021-01-04,USD,14,29,202,3,6,0.050,3202.6,1921.560
7988,SO - 0008089,Online,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-23,2021-01-26,USD,14,32,241,35,5,0.200,3825.7,2792.761
7989,SO - 0008090,Online,WARE-NMK1003,2020-09-26,2020-12-30,2021-01-20,2021-01-25,USD,20,42,112,36,8,0.100,1072.0,804.000
7990,SO - 0008091,In-Store,WARE-UHY1004,2020-09-26,2020-12-30,2021-01-13,2021-01-19,USD,6,41,237,43,5,0.075,2211.0,1370.820

In [211]:
pd.ExcelFile("US_Regional_Sales_Data.xlsx").sheet_names

['Sales Orders Sheet',
 'Customers Sheet',
 'Store Locations Sheet',
 'Products Sheet',
 'Sales Team Sheet']

In [212]:
df_sales = pd.read_excel("US_Regional_Sales_Data.xlsx", sheet_name = 'Sales Orders Sheet')

df_customers = pd.read_excel("US_Regional_Sales_Data.xlsx", sheet_name = 'Customers Sheet')

df_stores = pd.read_excel("US_Regional_Sales_Data.xlsx", sheet_name = 'Store Locations Sheet')

df_products = pd.read_excel("US_Regional_Sales_Data.xlsx", sheet_name = 'Products Sheet')

df_teams = pd.read_excel("US_Regional_Sales_Data.xlsx", sheet_name = 'Sales Team Sheet')

In [213]:
#2. Cruza todos los DataFrames usando validación many_to_one, y guarda el resultado en una nueva variable llamada df_base.

In [214]:
df_base = df_sales.merge(df_customers, validate = 'many_to_one').\
                   merge(df_stores, validate = 'many_to_one').\
                   merge(df_products, validate = 'many_to_one').\
                   merge(df_teams, validate = 'many_to_one')

In [215]:
df_base.head()

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,AreaCode,Population,Household Income,Median Income,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,631,213776,68789,80327,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,478,153515,57025,36568,645603627,14488557,America/New York,Dining Furniture,Joshua Bennett,Northeast
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,719,456568,174441,54527,506667557,947196,America/Denver,Dining Furniture,Joshua Bennett,Northeast
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,716,258071,110549,31918,104592941,31362925,America/New York,Dining Furniture,Joshua Bennett,Northeast
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,702,223182,88401,43911,121034884,0,America/Los Angeles,Dining Furniture,Joshua Bennett,Northeast

In [216]:
df_base.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7991 entries, 0 to 7990
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderNumber       7991 non-null   object
 1   Sales Channel     7991 non-null   object
 2   WarehouseCode     7991 non-null   object
 3   ProcuredDate      7991 non-null   datetime64[ns]
 4   OrderDate         7991 non-null   datetime64[ns]
 5   ShipDate          7991 non-null   datetime64[ns]
 6   DeliveryDate      7991 non-null   datetime64[ns]
 7   CurrencyCode      7991 non-null   object
 8   _SalesTeamID      7991 non-null   int64
 9   _CustomerID       7991 non-null   int64
 10  _StoreID          7991 non-null   int64
 11  _ProductID        7991 non-null   int64
 12  Order Quantity    7991 non-null   int64
 13  Discount Applied  7991 non-null   float64
 14  Unit Price        7991 non-null   float64
 15  Unit Cost         7991 non-null   float64
 16  Customer Names    7991 non-null   object
 17  City Name         7991 non-null   object
 18  County            7991 non-null   object
 19  StateCode         7991 non-null   object
 20  State             7991 non-null   object
 21  Type              7991 non-null   object
 22  Latitude          7991 non-null   float64
 23  Longitude         7991 non-null   float64
 24  AreaCode          7991 non-null   int64
 25  Population        7991 non-null   int64
 26  Household Income  7991 non-null   int64
 27  Median Income     7991 non-null   int64
 28  Land Area         7991 non-null   int64
 29  Water Area        7991 non-null   int64
 30  Time Zone         7991 non-null   object
 31  Product Name      7991 non-null   object
 32  Sales Team        7991 non-null   object
 33  Region            7991 non-null   object
dtypes: datetime64[ns](4), float64(5), int64(11), object(14)
memory usage: 2.1+ MB

In [217]:
#3. Agrega las siguientes columnas a df_ base:
#ProcurementDays OrderDate-ProcuredDate
#ShippingDays ShipDate-OrderDate
#DeliveryDays DeliveryDate-ShipDate
#CustomerDays ShippingDays+DeliveryDays

In [218]:
df_base["ProcurementDays"]=df_base["OrderDate"]-df_base["ProcuredDate"]
df_base["ShippingDays"]=df_base["ShipDate"]-df_base["OrderDate"]
df_base["DeliveryDays"]=df_base["DeliveryDate"]-df_base["ShipDate"]
df_base["CustomerDays"]=df_base["ShippingDays"]+df_base["DeliveryDays"]
df_base.head()

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,Land Area,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,135481314,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19 days
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,645603627,14488557,America/New York,Dining Furniture,Joshua Bennett,Northeast,130 days,19 days,5 days,24 days
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,506667557,947196,America/Denver,Dining Furniture,Joshua Bennett,Northeast,113 days,2 days,6 days,8 days
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,104592941,31362925,America/New York,Dining Furniture,Joshua Bennett,Northeast,152 days,6 days,3 days,9 days
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,121034884,0,America/Los Angeles,Dining Furniture,Joshua Bennett,Northeast,122 days,8 days,4 days,12 days

In [219]:
#4. Agrega una nueva columna discreta al df_base, con el nombre CustomerDaysInterval
#que clasifique los valores de la columna CustomerDays en los siguientes intervalos:
#0 to 15 days
#15 to 30 days
#30 to 45 days
#45 to 60 days
#60 to 75 days
#75 to 90 days

In [220]:
# Discretizar los datos en intervalos
intervalos = [0, 15, 30, 45, 60, 75, 90]  
# Definir los intervalos deseados
etiquetas = [0, 1, 2, 3, 4, 5]  # Etiquetas numéricas para las categorías

# Convertir la columna CustomerDays en numérica y dividirla por 86400000000000 
df_base["CustomerDays"] = pd.to_numeric(df_base["CustomerDays"]) //86400000000000


# Discretizar y devolver valores en lugar de intervalos
df_base["CustomerDaysInterval"] = pd.cut(df_base["CustomerDays"], bins=intervalos, labels=etiquetas, right=False)

df_base

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,Water Area,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,160302131,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,1
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,14488557,America/New York,Dining Furniture,Joshua Bennett,Northeast,130 days,19 days,5 days,24,1
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,947196,America/Denver,Dining Furniture,Joshua Bennett,Northeast,113 days,2 days,6 days,8,0
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,31362925,America/New York,Dining Furniture,Joshua Bennett,Northeast,152 days,6 days,3 days,9,0
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,0,America/Los Angeles,Dining Furniture,Joshua Bennett,Northeast,122 days,8 days,4 days,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0003465,In-Store,WARE-PUJ1005,2019-05-15,2019-06-30,2019-07-27,2019-08-01,USD,11,35,...,3788915,America/Chicago,Pillows,Joshua Little,South,46 days,27 days,5 days,32,2
7987,SO - 0002097,In-Store,WARE-MKL1006,2018-10-27,2019-01-16,2019-02-13,2019-02-23,USD,11,39,...,3870729,America/Chicago,Pillows,Joshua Little,South,81 days,28 days,10 days,38,2
7988,SO - 0001648,In-Store,WARE-NMK1003,2018-07-19,2018-12-02,2018-12-22,2018-12-29,USD,11,17,...,2423679,America/Chicago,Pillows,Joshua Little,South,136 days,20 days,7 days,27,1
7989,SO - 0006241,In-Store,WARE-XYS1001,2019-12-01,2020-05-29,2020-06-04,2020-06-11,USD,11,44,...,1950781,America/Phoenix,Bathroom Furniture,Joshua Little,South,180 days,6 days,7 days,13,0
7990,SO - 000645,In-Store,WARE-PUJ1005,2018-04-10,2018-08-04,2018-08-27,2018-09-02,USD,11,13,...,30147582,America/Los Angeles,Bathroom Furniture,Joshua Little,South,116 days,23 days,6 days,29,1

In [221]:
#5. Utiliza una tabla pivote para mostrar el conteo de órdenes agrupando por SalesTeam en las filas y CustomerDaysInterval en las columnas. 
#Este reporte debe cuadrar con los datos de la pestaña Reporte1 del archivo reportes.xlsx

In [222]:
df_pivot_1 = pd.pivot_table(
                                   data = df_base 
                                 , index = "Sales Team" 
                                 , columns= "CustomerDaysInterval"
                                 , values = "OrderNumber" 
                                 , aggfunc= "count" 
                                 , margins = True 
)

df_pivot_1

CustomerDaysInterval     0     1     2    3    4    5   All
Sales Team
Adam Hernandez          71   176    55  0.0  0.0  0.0   302
Anthony Berry           69   176    53  0.0  0.0  0.0   298
Anthony Torres          70   160    58  0.0  0.0  0.0   288
Carl Nguyen             85   184    45  0.0  0.0  0.0   314
Carlos Miller           56   145    46  0.0  0.0  0.0   247
Chris Armstrong         86   152    54  0.0  0.0  0.0   292
Donald Reynolds         87   167    42  0.0  0.0  0.0   296
Douglas Tucker          76   148    53  0.0  0.0  0.0   277
Frank Brown             71   156    48  0.0  0.0  0.0   275
George Lewis            92   169    54  0.0  0.0  0.0   315
Jerry Green             81   162    53  0.0  0.0  0.0   296
Joe Price               80   129    57  0.0  0.0  0.0   266
Jonathan Hawkins        74   141    45  0.0  0.0  0.0   260
Joshua Bennett          79   148    38  0.0  0.0  0.0   265
Joshua Little           74   166    49  0.0  0.0  0.0   289
Joshua Ryan             76   166    43  0.0  0.0  0.0   285
Keith Griffin           84   130    32  0.0  0.0  0.0   246
Nicholas Cunningham     79   167    47  0.0  0.0  0.0   293
Patrick Graham          78   139    42  0.0  0.0  0.0   259
Paul Holmes             51   163    47  0.0  0.0  0.0   261
Roger Alexander         65   159    47  0.0  0.0  0.0   271
Roy Rice                65   166    53  0.0  0.0  0.0   284
Samuel Fowler           81   164    51  0.0  0.0  0.0   296
Shawn Cook              75   175    53  0.0  0.0  0.0   303
Shawn Torres            68   164    42  0.0  0.0  0.0   274
Shawn Wallace           86   173    57  0.0  0.0  0.0   316
Stephen Payne           87   151    45  0.0  0.0  0.0   283
Todd Roberts           103   185    52  0.0  0.0  0.0   340
All                   2149  4481  1361  NaN  NaN  NaN  7991

In [223]:
#6. Agrega la siguiente columna calculada a la base:
#KPI Cálculo
#GrossMargin OrderQuantity*(UnitPrice*(1-Discount Applied)-UnitCost)

In [224]:
df_base.columns

Index(['OrderNumber', 'Sales Channel', 'WarehouseCode', 'ProcuredDate',
       'OrderDate', 'ShipDate', 'DeliveryDate', 'CurrencyCode', '_SalesTeamID',
       '_CustomerID', '_StoreID', '_ProductID', 'Order Quantity',
       'Discount Applied', 'Unit Price', 'Unit Cost', 'Customer Names',
       'City Name', 'County', 'StateCode', 'State', 'Type', 'Latitude',
       'Longitude', 'AreaCode', 'Population', 'Household Income',
       'Median Income', 'Land Area', 'Water Area', 'Time Zone', 'Product Name',
       'Sales Team', 'Region', 'ProcurementDays', 'ShippingDays',
       'DeliveryDays', 'CustomerDays', 'CustomerDaysInterval'],
      dtype='object')

In [225]:
df_base["GrossMargin"] = df_base["Order Quantity"]*(df_base["Unit Price"]*(1-df_base["Discount Applied"])-df_base["Unit Cost"])
df_base

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,Time Zone,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,America/New York,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,1,4073.4325
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,America/New York,Dining Furniture,Joshua Bennett,Northeast,130 days,19 days,5 days,24,1,1988.0910
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,America/Denver,Dining Furniture,Joshua Bennett,Northeast,113 days,2 days,6 days,8,0,2185.2720
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,America/New York,Dining Furniture,Joshua Bennett,Northeast,152 days,6 days,3 days,9,0,4296.3750
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,America/Los Angeles,Dining Furniture,Joshua Bennett,Northeast,122 days,8 days,4 days,12,0,1118.5650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0003465,In-Store,WARE-PUJ1005,2019-05-15,2019-06-30,2019-07-27,2019-08-01,USD,11,35,...,America/Chicago,Pillows,Joshua Little,South,46 days,27 days,5 days,32,2,643.8700
7987,SO - 0002097,In-Store,WARE-MKL1006,2018-10-27,2019-01-16,2019-02-13,2019-02-23,USD,11,39,...,America/Chicago,Pillows,Joshua Little,South,81 days,28 days,10 days,38,2,763.8000
7988,SO - 0001648,In-Store,WARE-NMK1003,2018-07-19,2018-12-02,2018-12-22,2018-12-29,USD,11,17,...,America/Chicago,Pillows,Joshua Little,South,136 days,20 days,7 days,27,1,1763.1720
7989,SO - 0006241,In-Store,WARE-XYS1001,2019-12-01,2020-05-29,2020-06-04,2020-06-11,USD,11,44,...,America/Phoenix,Bathroom Furniture,Joshua Little,South,180 days,6 days,7 days,13,0,1917.5400
7990,SO - 000645,In-Store,WARE-PUJ1005,2018-04-10,2018-08-04,2018-08-27,2018-09-02,USD,11,13,...,America/Los Angeles,Bathroom Furniture,Joshua Little,South,116 days,23 days,6 days,29,1,-553.5540

In [226]:
#7. En esta parte debes aplicar un porcentaje a la columna GrossMargin,
#pero ese porcentaje dependerá del intervalo en que se encuentre GrossMargin.

In [227]:
# Discretizar los datos en intervalos
intervalos_margen = [0, 100, 1000, 10000, 100000]  
# Definir los intervalos deseados
etiquetas_margen = [0.05, 0.10, 0.15, 0.20]  # Etiquetas numéricas para las categorías

# Discretizar y devolver valores en lugar de intervalos
df_base["CommissionsPercentage"] = pd.cut(df_base["GrossMargin"], bins=intervalos_margen, labels=etiquetas_margen, right=False)

#Numérico

df_base["CommissionsPercentage"] = pd.to_numeric(df_base["CommissionsPercentage"])

df_base

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,Product Name,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin,CommissionsPercentage
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,Dining Furniture,Joshua Bennett,Northeast,151 days,14 days,5 days,19,1,4073.4325,0.15
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,Dining Furniture,Joshua Bennett,Northeast,130 days,19 days,5 days,24,1,1988.0910,0.15
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,Dining Furniture,Joshua Bennett,Northeast,113 days,2 days,6 days,8,0,2185.2720,0.15
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,Dining Furniture,Joshua Bennett,Northeast,152 days,6 days,3 days,9,0,4296.3750,0.15
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,Dining Furniture,Joshua Bennett,Northeast,122 days,8 days,4 days,12,0,1118.5650,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0003465,In-Store,WARE-PUJ1005,2019-05-15,2019-06-30,2019-07-27,2019-08-01,USD,11,35,...,Pillows,Joshua Little,South,46 days,27 days,5 days,32,2,643.8700,0.10
7987,SO - 0002097,In-Store,WARE-MKL1006,2018-10-27,2019-01-16,2019-02-13,2019-02-23,USD,11,39,...,Pillows,Joshua Little,South,81 days,28 days,10 days,38,2,763.8000,0.10
7988,SO - 0001648,In-Store,WARE-NMK1003,2018-07-19,2018-12-02,2018-12-22,2018-12-29,USD,11,17,...,Pillows,Joshua Little,South,136 days,20 days,7 days,27,1,1763.1720,0.15
7989,SO - 0006241,In-Store,WARE-XYS1001,2019-12-01,2020-05-29,2020-06-04,2020-06-11,USD,11,44,...,Bathroom Furniture,Joshua Little,South,180 days,6 days,7 days,13,0,1917.5400,0.15
7990,SO - 000645,In-Store,WARE-PUJ1005,2018-04-10,2018-08-04,2018-08-27,2018-09-02,USD,11,13,...,Bathroom Furniture,Joshua Little,South,116 days,23 days,6 days,29,1,-553.5540,NaN

In [228]:
#8. Calcula el monto de la comisión, utilizando la Tabla del Anexo

In [229]:
df_base["CommissionsAmount"] = df_base["GrossMargin"]*df_base["CommissionsPercentage"]
df_base

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,Sales Team,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin,CommissionsPercentage,CommissionsAmount
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,Joshua Bennett,Northeast,151 days,14 days,5 days,19,1,4073.4325,0.15,611.014875
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,Joshua Bennett,Northeast,130 days,19 days,5 days,24,1,1988.0910,0.15,298.213650
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,Joshua Bennett,Northeast,113 days,2 days,6 days,8,0,2185.2720,0.15,327.790800
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,Joshua Bennett,Northeast,152 days,6 days,3 days,9,0,4296.3750,0.15,644.456250
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,Joshua Bennett,Northeast,122 days,8 days,4 days,12,0,1118.5650,0.15,167.784750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0003465,In-Store,WARE-PUJ1005,2019-05-15,2019-06-30,2019-07-27,2019-08-01,USD,11,35,...,Joshua Little,South,46 days,27 days,5 days,32,2,643.8700,0.10,64.387000
7987,SO - 0002097,In-Store,WARE-MKL1006,2018-10-27,2019-01-16,2019-02-13,2019-02-23,USD,11,39,...,Joshua Little,South,81 days,28 days,10 days,38,2,763.8000,0.10,76.380000
7988,SO - 0001648,In-Store,WARE-NMK1003,2018-07-19,2018-12-02,2018-12-22,2018-12-29,USD,11,17,...,Joshua Little,South,136 days,20 days,7 days,27,1,1763.1720,0.15,264.475800
7989,SO - 0006241,In-Store,WARE-XYS1001,2019-12-01,2020-05-29,2020-06-04,2020-06-11,USD,11,44,...,Joshua Little,South,180 days,6 days,7 days,13,0,1917.5400,0.15,287.631000
7990,SO - 000645,In-Store,WARE-PUJ1005,2018-04-10,2018-08-04,2018-08-27,2018-09-02,USD,11,13,...,Joshua Little,South,116 days,23 days,6 days,29,1,-553.5540,NaN,NaN

In [230]:
#9. Calcula la comisión sobre el margen bruto.

In [231]:
df_base["NetMargin"] = df_base["GrossMargin"]-df_base["CommissionsAmount"]
df_base

,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,...,Region,ProcurementDays,ShippingDays,DeliveryDays,CustomerDays,CustomerDaysInterval,GrossMargin,CommissionsPercentage,CommissionsAmount,NetMargin
0,SO - 000101,In-Store,WARE-UHY1004,2017-12-31,2018-05-31,2018-06-14,2018-06-19,USD,6,15,...,Northeast,151 days,14 days,5 days,19,1,4073.4325,0.15,611.014875,3462.417625
1,SO - 0002491,In-Store,WARE-NMK1003,2018-10-27,2019-03-06,2019-03-25,2019-03-30,USD,6,11,...,Northeast,130 days,19 days,5 days,24,1,1988.0910,0.15,298.213650,1689.877350
2,SO - 0001458,In-Store,WARE-NMK1003,2018-07-19,2018-11-09,2018-11-11,2018-11-17,USD,6,12,...,Northeast,113 days,2 days,6 days,8,0,2185.2720,0.15,327.790800,1857.481200
3,SO - 0005166,In-Store,WARE-PUJ1005,2019-08-23,2020-01-22,2020-01-28,2020-01-31,USD,6,7,...,Northeast,152 days,6 days,3 days,9,0,4296.3750,0.15,644.456250,3651.918750
4,SO - 0002439,In-Store,WARE-UHY1004,2018-10-27,2019-02-26,2019-03-06,2019-03-10,USD,6,33,...,Northeast,122 days,8 days,4 days,12,0,1118.5650,0.15,167.784750,950.780250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0003465,In-Store,WARE-PUJ1005,2019-05-15,2019-06-30,2019-07-27,2019-08-01,USD,11,35,...,South,46 days,27 days,5 days,32,2,643.8700,0.10,64.387000,579.483000
7987,SO - 0002097,In-Store,WARE-MKL1006,2018-10-27,2019-01-16,2019-02-13,2019-02-23,USD,11,39,...,South,81 days,28 days,10 days,38,2,763.8000,0.10,76.380000,687.420000
7988,SO - 0001648,In-Store,WARE-NMK1003,2018-07-19,2018-12-02,2018-12-22,2018-12-29,USD,11,17,...,South,136 days,20 days,7 days,27,1,1763.1720,0.15,264.475800,1498.696200
7989,SO - 0006241,In-Store,WARE-XYS1001,2019-12-01,2020-05-29,2020-06-04,2020-06-11,USD,11,44,...,South,180 days,6 days,7 days,13,0,1917.5400,0.15,287.631000,1629.909000
7990,SO - 000645,In-Store,WARE-PUJ1005,2018-04-10,2018-08-04,2018-08-27,2018-09-02,USD,11,13,...,South,116 days,23 days,6 days,29,1,-553.5540,NaN,NaN,NaN

In [232]:
#10. Utilizando una tabla pivote, muestra la suma de los valores GrossMargin, NetMargin y
#CommissionAmount agrupando por Sales Team en las filas. Este reporte debe cuadrar con
#los datos de la pestaña Reporte2 del archivo reportes.xlsx

In [233]:
df_pivot_2 = pd.pivot_table(
                                   data = df_base 
                                 , index = "Sales Team"
                                 , values = ["GrossMargin", "NetMargin", "CommissionsAmount"] 
                                 , aggfunc= "sum" 
                                 , margins = True 
)

df_pivot_2

                     CommissionsAmount   GrossMargin     NetMargin
Sales Team
Adam Hernandez            1.266372e+05  7.790952e+05  6.779873e+05
Anthony Berry             1.240612e+05  7.679440e+05  6.547983e+05
Anthony Torres            1.179622e+05  7.439014e+05  6.367580e+05
Carl Nguyen               1.238432e+05  7.747815e+05  6.618747e+05
Carlos Miller             1.108821e+05  6.687529e+05  5.803260e+05
Chris Armstrong           1.225657e+05  7.816087e+05  6.608574e+05
Donald Reynolds           1.437683e+05  8.853868e+05  7.540383e+05
Douglas Tucker            1.208064e+05  7.455286e+05  6.337861e+05
Frank Brown               1.048395e+05  6.708813e+05  5.700768e+05
George Lewis              1.368523e+05  8.391507e+05  7.108248e+05
Jerry Green               1.266604e+05  7.885878e+05  6.703790e+05
Joe Price                 1.288229e+05  7.877074e+05  6.626621e+05
Jonathan Hawkins          1.262169e+05  7.813916e+05  6.646299e+05
Joshua Bennett            1.080491e+05  6.617265e+05  5.692421e+05
Joshua Little             1.358062e+05  8.403212e+05  7.139012e+05
Joshua Ryan               1.142049e+05  7.021578e+05  6.069049e+05
Keith Griffin             1.129401e+05  6.754536e+05  5.996883e+05
Nicholas Cunningham       1.278330e+05  7.926449e+05  6.831646e+05
Patrick Graham            1.216509e+05  7.463940e+05  6.322861e+05
Paul Holmes               1.142249e+05  7.055646e+05  5.988674e+05
Roger Alexander           1.224879e+05  7.730277e+05  6.583238e+05
Roy Rice                  1.345471e+05  8.314466e+05  7.068772e+05
Samuel Fowler             1.293671e+05  7.932549e+05  6.712090e+05
Shawn Cook                1.359863e+05  8.548780e+05  7.243492e+05
Shawn Torres              1.142910e+05  7.056196e+05  6.009504e+05
Shawn Wallace             1.169421e+05  7.267377e+05  6.242365e+05
Stephen Payne             1.161115e+05  7.071568e+05  6.062416e+05
Todd Roberts              1.258321e+05  7.942254e+05  6.921236e+05
All                       3.444193e+06  2.167156e+07  1.822736e+07

In [234]:
#Sugerencia de compañero. Desconozco el motivo por el cual aparece en notación científica, dado que los datos ya son float.
df_pivot_2 = df_pivot_2.applymap(lambda x: "{:.2f}".format(x))
df_pivot_2

                    CommissionsAmount  GrossMargin    NetMargin
Sales Team
Adam Hernandez              126637.21    779095.20    677987.33
Anthony Berry               124061.18    767943.95    654798.34
Anthony Torres              117962.21    743901.44    636758.05
Carl Nguyen                 123843.21    774781.47    661874.73
Carlos Miller               110882.09    668752.93    580326.02
Chris Armstrong             122565.71    781608.70    660857.42
Donald Reynolds             143768.34    885386.81    754038.26
Douglas Tucker              120806.40    745528.56    633786.05
Frank Brown                 104839.47    670881.25    570076.79
George Lewis                136852.26    839150.75    710824.78
Jerry Green                 126660.44    788587.76    670379.03
Joe Price                   128822.93    787707.44    662662.11
Jonathan Hawkins            126216.95    781391.59    664629.88
Joshua Bennett              108049.11    661726.54    569242.06
Joshua Little               135806.23    840321.17    713901.23
Joshua Ryan                 114204.91    702157.82    606904.87
Keith Griffin               112940.12    675453.60    599688.29
Nicholas Cunningham         127833.00    792644.94    683164.58
Patrick Graham              121650.86    746394.00    632286.07
Paul Holmes                 114224.89    705564.60    598867.37
Roger Alexander             122487.90    773027.68    658323.84
Roy Rice                    134547.05    831446.62    706877.20
Samuel Fowler               129367.15    793254.88    671208.95
Shawn Cook                  135986.30    854878.02    724349.21
Shawn Torres                114290.96    705619.61    600950.39
Shawn Wallace               116942.05    726737.68    624236.47
Stephen Payne               116111.48    707156.79    606241.58
Todd Roberts                125832.14    794225.37    692123.62
All                        3444192.55  21671557.09  18227364.54